name: Deploy MercadoPago Service Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Corre diariamente
  workflow_dispatch:      # Permite ejecutar manualmente
  push:
    branches: [ "main" ]  # Solo en la rama principal
  issues:
    types: [opened, closed, edited, deleted]
  milestone:
    types: [created, closed, edited, deleted]

# Permisos actualizados
permissions:
  contents: write    # Para repo y wiki
  pages: write      # Para GitHub Pages
  id-token: write   # Para autenticación
  issues: write     # Para issues
  pull-requests: write  # Para PR y merge
  repository-projects: write
  actions: write    # Para acceder a las acciones
  deployments: write    # Para despliegues
  statuses: write       # Para actualizar estados
  wiki: write       # Permiso específico para wiki

env:
  WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}

jobs:
  build:
    name: Build MercadoPago Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MercadoPago Service
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WIKI_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub markdown2 jinja2 requests

      - name: Fetch MercadoPago Service Issues and Milestones
        env:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          python scripts/fetch_github_data.py

      - name: Generate MercadoPago Documentation
        run: |
          python scripts/generate_docs.py

      - name: Generate MercadoPago Wiki
        env:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          git config --global user.name "EchavarriaLander"
          git config --global user.email "l.echavarria@alumno.um.edu.ar"
          python scripts/generate_wiki.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      
  deploy:
    name: Deploy MercadoPago Documentation
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MercadoPago Documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 